<a href="https://colab.research.google.com/github/chriscabezash/TEST/blob/master/Censo_2017_Viviendas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gdown
import pandas as pd

# ID del archivo en Google Drive

#file_id = '1l-nXjqdxJatyDWVPcwKxOWWLoKhzRQFd'
file_id = '18hut4BbMh_ugu3Zp-SMJyacegSILc0Pi'

# URL del archivo
url = f'https://drive.google.com/uc?id={file_id}'

# Descargar el archivo
output = 'file.csv'
gdown.download(url, output, quiet=False)

# Leer el archivo CSV
df = pd.read_csv(output, delimiter=';')

# Mostrar el DataFrame
df

Downloading...
From (original): https://drive.google.com/uc?id=18hut4BbMh_ugu3Zp-SMJyacegSILc0Pi
From (redirected): https://drive.google.com/uc?id=18hut4BbMh_ugu3Zp-SMJyacegSILc0Pi&confirm=t&uuid=47410146-34a4-4ad8-8984-b9aae1571c85
To: /content/file.csv
100%|██████████| 380M/380M [00:08<00:00, 47.5MB/s]

,REGION,PROVINCIA,COMUNA,DC,AREA,ZC_LOC,ID_ZONA_LOC,NVIV,P01,P02,P03A,P03B,P03C,P04,P05,CANT_HOG,CANT_PER,REGION_15R,PROVINCIA_15R,COMUNA_15R
0,15,152,15202,1,2,6,13225,1,3,1,5,3,5,1,4,1,1,15,152,15202
1,15,152,15202,1,2,6,13225,2,1,3,98,98,98,98,98,0,0,15,152,15202
2,15,152,15202,1,2,6,13225,3,1,1,5,3,5,2,3,1,4,15,152,15202
3,15,152,15202,1,2,6,13225,4,1,4,98,98,98,98,98,0,0,15,152,15202
4,15,152,15202,1,2,6,13225,5,3,4,98,98,98,98,98,0,0,15,152,15202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499569,1,11,1101,99,1,999,12486,232,1,1,3,3,1,2,1,1,3,1,11,1101
6499570,1,11,1101,99,1,999,12486,233,1,1,2,3,1,1,1,1,2,1,11,1101
6499571,1,11,1101,99,1,999,12486,234,4,1,4,3,1,0,1,1,1,1,11,1101
6499572,1,11,1101,99,1,999,12486,235,4,1,3,3,1,0,1,1,1,1,11,1101
6499573,1,11,1101,99,1,999,12486,236,1,1,2,2,1,3,1,1,3,1,11,1101

In [ ]:
df.describe()

,REGION,PROVINCIA,COMUNA,DC,AREA,ZC_LOC,ID_ZONA_LOC,NVIV,P01,P02,P03A,P03B,P03C,P04,P05,CANT_HOG,CANT_PER,REGION_15R,PROVINCIA_15R,COMUNA_15R
count,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06,6.499574e+06
mean,9.387927e+00,9.580448e+01,9.587300e+03,6.851055e+00,1.148535e+00,1.262980e+01,7.984414e+03,6.038110e+02,1.301122e+00,1.306294e+00,1.719055e+01,1.763030e+01,1.664236e+01,1.976650e+01,1.647445e+01,1.066171e+00,2.703870e+00,9.148448e+00,9.348255e+01,9.355254e+03
std,3.953171e+00,3.923588e+01,3.926389e+03,7.617056e+00,3.556294e-01,7.891399e+01,4.650845e+03,4.994824e+02,8.148972e-01,7.885367e-01,3.478485e+01,3.489619e+01,3.547724e+01,3.681592e+01,3.539488e+01,4.367206e+00,6.026778e+00,3.784064e+00,3.753342e+01,3.756477e+03
min,1.000000e+00,1.100000e+01,1.101000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.100000e+01,1.101000e+03
25%,6.000000e+00,6.100000e+01,6.102000e+03,2.000000e+00,1.000000e+00,2.000000e+00,3.928000e+03,1.870000e+02,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+00,6.100000e+01,6.102000e+03
50%,9.000000e+00,9.200000e+01,9.211000e+03,5.000000e+00,1.000000e+00,3.000000e+00,7.903000e+03,5.030000e+02,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,9.000000e+00,9.100000e+01,9.111000e+03
75%,1.300000e+01,1.310000e+02,1.312000e+04,9.000000e+00,1.000000e+00,6.000000e+00,1.204800e+04,9.110000e+02,1.000000e+00,1.000000e+00,3.000000e+00,3.000000e+00,1.000000e+00,4.000000e+00,1.000000e+00,1.000000e+00,4.000000e+00,1.300000e+01,1.310000e+02,1.311900e+04
max,1.600000e+01,1.630000e+02,1.630500e+04,9.900000e+01,2.000000e+00,9.990000e+02,1.605300e+04,4.301000e+03,1.000000e+01,4.000000e+00,9.900000e+01,9.900000e+01,9.900000e+01,9.900000e+01,9.900000e+01,9.800000e+01,5.912000e+03,1.500000e+01,1.520000e+02,1.520200e+04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6499574 entries, 0 to 6499573
Data columns (total 20 columns):
 #   Column         Dtype
---  ------         -----
 0   REGION         int64
 1   PROVINCIA      int64
 2   COMUNA         int64
 3   DC             int64
 4   AREA           int64
 5   ZC_LOC         int64
 6   ID_ZONA_LOC    int64
 7   NVIV           int64
 8   P01            int64
 9   P02            int64
 10  P03A           int64
 11  P03B           int64
 12  P03C           int64
 13  P04            int64
 14  P05            int64
 15  CANT_HOG       int64
 16  CANT_PER       int64
 17  REGION_15R     int64
 18  PROVINCIA_15R  int64
 19  COMUNA_15R     int64
dtypes: int64(20)
memory usage: 991.8 MB